########################################################################################################################
# Memo:
########################################################################################################################

# This file is used to configure files/folders to copy and folder links to create (before running premake).

# Mappings ($ string substitutions). Name and examples:
# |==========================================================
# | $platform      | 'windows-x86_64'     | 'linux-x86_64'  | 
# |----------------------------------------------------------
# | $lib_ext       | '.dll'               | '.so'           |
# | $lib_prefix    | ''                   | 'lib.'          |
# | $bindings_ext  | '.pyd'               | '.so'           |
# | $exe_ext       | '.exe'               | ''              |
# | $shell_ext     | '.bat'               | '.sh'           |
# |==========================================================
#
# |==========================================================
# | $config        | 'debug'              | 'release'       |
# |==========================================================

# Filters. For example, debug config on linux-x86_64 matches all those toml keys:
# [linux-x86_64]
# [debug]
# [linux.debug]
# So you can use those in any order as a keys: ["linux-x86_64", "debug", "linux", "x86_64"]


########################################################################################################################
# NOTE:
# This file is almost empty, we prefer to use the second one: _build/generated/prebuild.toml. It is generated by premake
# configurations. That allows to keep all copy and link configuration together with other project data.
########################################################################################################################


########################################################################################################################
# Common section:
########################################################################################################################

copy = [
    ["_build/target-deps/usd/$config/lib/*$lib_ext*", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/usd", "_build/$platform/$config/usd"],
    ["_build/target-deps/usd/$config/lib/python", "_build/$platform/$config/python"],

    ["_build/target-deps/usd_ext_physics/$config/lib/*$lib_ext", "_build/$platform/$config"],
    ["_build/target-deps/usd_ext_physics/$config/lib/python", "_build/$platform/$config/python/pxr"],
    ["_build/target-deps/usd_ext_physics/$config/share/usd/plugins/UsdPhysics/**/*.*", "_build/$platform/$config/usd/UsdPhysics"],
    
    ["_build/target-deps/omni_usd_resolver/$config/**/*.*", "_build/$platform/$config"],
    ["_build/target-deps/omni_client_library/$config", "_build/$platform/$config"],

    ["_build/target-deps/omni_asset_validator/$config/**/*.*", "_build/$platform/$config"],
    ["_build/target-deps/carb_sdk_plugins/_build/$platform/$config/*carb$lib_ext*", "_build/$platform/$config"],
    ["_build/target-deps/carb_sdk_plugins/_build/$platform/$config/*tokens.*", "_build/$platform/$config"],
    ["_build/target-deps/carb_sdk_plugins/_build/$platform/$config/*dictionary.*", "_build/$platform/$config"],
    ["_build/target-deps/carb_sdk_plugins/_build/$platform/$config/*settings.*", "_build/$platform/$config"],
    ["_build/target-deps/carb_sdk_plugins/_build/$platform/$config/*crashreporter-breakpad.*", "_build/$platform/$config"],
    ["_build/target-deps/carb_sdk_plugins/_build/$platform/$config/bindings-python", "_build/$platform/$config/bindings-python"],

]
link = []


########################################################################################################################
# Windows platform:
########################################################################################################################

[windows-x86_64]
copy = [
    ["_build/target-deps/python/python3*$lib_ext", "_build/$platform/$config"],
    ["_build/host-deps/vc/bin/HostX64/x64/vcruntime*.*", "_build/$platform/release"],
]
link = []


########################################################################################################################
# Linux x86_64 platform:
########################################################################################################################

[linux-x86_64]
copy = [
    ["_build/target-deps/python/lib/*.*", "_build/$platform/$config"],
]
link = []
